### ISSUE TITLE
Done button causing fatal error due to unexpected nil?

### ISSUE THREAD

**Issue by bfatehi** [simonbs/BSKeyboardControls#59]
Im using swift 4.1 and xcode 9. I followed each of your steps but changed the obj c to swift.  When I press the done button in my app, it causes a fatal error: unexpected nil.  Also it does not scroll or change fields when i click the forward or prev arrows? Any ideas on what the problem is? I can post my code if necessary.

**Comment by brahm1695** [comment]
nevermind forgot to set their delegates to themselves

**Comment by bfatehi** [comment]
was simply due to i/o connection error. deleted the connection, created a new one and it worked.
